<?php

namespace Database\Seeders;

// use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class DatabaseSeeder extends Seeder
{
    /**
     * Seed the application's database.
     */
    public function run(): void
    {
        // \App\Models\User::factory(10)->create();

        // \App\Models\User::factory()->create([
        //     'name' => 'Test User',
        //     'email' => 'test@example.com',
        // ]);

        // Définition des données de test pour les pays
        $pays = [
            ['name' => 'Afghanistan', 'indicatif' => '+93'],
            ['name' => 'Albania', 'indicatif' => '+355'],
            ['name' => 'Algeria', 'indicatif' => '+213'],
            ['name' => 'American Samoa', 'indicatif' => '+1-684'],
            ['name' => 'Andorra', 'indicatif' => '+376'],
            ['name' => 'Angola', 'indicatif' => '+244'],
            ['name' => 'Anguilla', 'indicatif' => '+1-264'],
            ['name' => 'Antigua and Barbuda', 'indicatif' => '+1-268'],
            ['name' => 'Argentina', 'indicatif' => '+54'],
            ['name' => 'Armenia', 'indicatif' => '+374'],
            ['name' => 'Aruba', 'indicatif' => '+297'],
            ['name' => 'Australia', 'indicatif' => '+61'],
            ['name' => 'Austria', 'indicatif' => '+43'],
            ['name' => 'Azerbaijan', 'indicatif' => '+994'],
            ['name' => 'Bahamas', 'indicatif' => '+1-242'],
            ['name' => 'Bahrain', 'indicatif' => '+973'],
            ['name' => 'Bangladesh', 'indicatif' => '+880'],
            ['name' => 'Barbados', 'indicatif' => '+1-246'],
            ['name' => 'Belarus', 'indicatif' => '+375'],
            ['name' => 'Belgium', 'indicatif' => '+32'],
            ['name' => 'Belize', 'indicatif' => '+501'],
            ['name' => 'Benin', 'indicatif' => '+229'],
            ['name' => 'Bermuda', 'indicatif' => '+1-441'],
            ['name' => 'Bhutan', 'indicatif' => '+975'],
            ['name' => 'Bolivia', 'indicatif' => '+591'],
            ['name' => 'Bosnia and Herzegovina', 'indicatif' => '+387'],
            ['name' => 'Botswana', 'indicatif' => '+267'],
            ['name' => 'Brazil', 'indicatif' => '+55'],
            ['name' => 'British Indian Ocean Territory', 'indicatif' => '+246'],
            ['name' => 'British Virgin Islands', 'indicatif' => '+1-284'],
            ['name' => 'Brunei', 'indicatif' => '+673'],
            ['name' => 'Bulgaria', 'indicatif' => '+359'],
            ['name' => 'Burkina Faso', 'indicatif' => '+226'],
            ['name' => 'Burundi', 'indicatif' => '+257'],
            ['name' => 'Cambodia', 'indicatif' => '+855'],
            ['name' => 'Cameroon', 'indicatif' => '+237'],
            ['name' => 'Canada', 'indicatif' => '+1'],
            ['name' => 'Cape Verde', 'indicatif' => '+238'],
            ['name' => 'Cayman Islands', 'indicatif' => '+1-345'],
            ['name' => 'Central African Republic', 'indicatif' => '+236'],
            ['name' => 'Chad', 'indicatif' => '+235'],
            ['name' => 'Chile', 'indicatif' => '+56'],
            ['name' => 'China', 'indicatif' => '+86'],
            ['name' => 'Christmas Island', 'indicatif' => '+61'],
            ['name' => 'Cocos Islands', 'indicatif' => '+61'],
            ['name' => 'Colombia', 'indicatif' => '+57'],
            ['name' => 'Comoros', 'indicatif' => '+269'],
            ['name' => 'Cook Islands', 'indicatif' => '+682'],
            ['name' => 'Costa Rica', 'indicatif' => '+506'],
            ['name' => 'Croatia', 'indicatif' => '+385'],
            ['name' => 'Cuba', 'indicatif' => '+53'],
            ['name' => 'Curacao', 'indicatif' => '+599'],
            ['name' => 'Cyprus', 'indicatif' => '+357'],
            ['name' => 'Czech Republic', 'indicatif' => '+420'],
            ['name' => 'Democratic Republic of the Congo', 'indicatif' => '+243'],
            ['name' => 'Denmark', 'indicatif' => '+45'],
            ['name' => 'Djibouti', 'indicatif' => '+253'],
            ['name' => 'Dominica', 'indicatif' => '+1-767'],
            ['name' => 'Dominican Republic', 'indicatif' => '+1-809'],
            ['name' => 'Ecuador', 'indicatif' => '+593'],
            ['name' => 'Egypt', 'indicatif' => '+20'],
            ['name' => 'El Salvador', 'indicatif' => '+503'],
            ['name' => 'Equatorial Guinea', 'indicatif' => '+240'],
            ['name' => 'Eritrea', 'indicatif' => '+291'],
            ['name' => 'Estonia', 'indicatif' => '+372'],
            ['name' => 'Ethiopia', 'indicatif' => '+251'],
            ['name' => 'Falkland Islands', 'indicatif' => '+500'],
            ['name' => 'Faroe Islands', 'indicatif' => '+298'],
            ['name' => 'Fiji', 'indicatif' => '+679'],
            ['name' => 'Finland', 'indicatif' => '+358'],
            ['name' => 'French Polynesia', 'indicatif' => '+689'],
            ['name' => 'Gabon', 'indicatif' => '+241'],
            ['name' => 'Gambia', 'indicatif' => '+220'],
            ['name' => 'Georgia', 'indicatif' => '+995'],
            ['name' => 'Germany', 'indicatif' => '+49'],
            ['name' => 'Ghana', 'indicatif' => '+233'],
            ['name' => 'Gibraltar', 'indicatif' => '+350'],
            ['name' => 'Greece', 'indicatif' => '+30'],
            ['name' => 'Greenland', 'indicatif' => '+299'],
            ['name' => 'Grenada', 'indicatif' => '+1-473'],
            ['name' => 'Guam', 'indicatif' => '+1-671'],
            ['name' => 'Guatemala', 'indicatif' => '+502'],
            ['name' => 'Guernsey', 'indicatif' => '+44-1481'],
            ['name' => 'Guinea', 'indicatif' => '+224'],
            ['name' => 'Guinea-Bissau', 'indicatif' => '+245'],
            ['name' => 'Guyana', 'indicatif' => '+592'],
            ['name' => 'Haiti', 'indicatif' => '+509'],
            ['name' => 'Honduras', 'indicatif' => '+504'],
            ['name' => 'Hong Kong', 'indicatif' => '+852'],
            ['name' => 'Hungary', 'indicatif' => '+36'],
            ['name' => 'Iceland', 'indicatif' => '+354'],
            ['name' => 'India', 'indicatif' => '+91'],
            ['name' => 'Indonesia', 'indicatif' => '+62'],
            ['name' => 'Iran', 'indicatif' => '+98'],
            ['name' => 'Iraq', 'indicatif' => '+964'],
            ['name' => 'Ireland', 'indicatif' => '+353'],
            ['name' => 'Isle of Man', 'indicatif' => '+44-1624'],
            ['name' => 'Israel', 'indicatif' => '+972'],
            ['name' => 'Italy', 'indicatif' => '+39'],
            ['name' => 'Ivory Coast', 'indicatif' => '+225'],
            ['name' => 'Jamaica', 'indicatif' => '+1-876'],
            ['name' => 'Japan', 'indicatif' => '+81'],
            ['name' => 'Jersey', 'indicatif' => '+44-1534'],
            ['name' => 'Jordan', 'indicatif' => '+962'],
            ['name' => 'Kazakhstan', 'indicatif' => '+7'],
            ['name' => 'Kenya', 'indicatif' => '+254'],
            ['name' => 'Kiribati', 'indicatif' => '+686'],
            ['name' => 'Kosovo', 'indicatif' => '+383'],
            ['name' => 'Kuwait', 'indicatif' => '+965'],
            ['name' => 'Kyrgyzstan', 'indicatif' => '+996'],
            ['name' => 'Laos', 'indicatif' => '+856'],
            ['name' => 'Latvia', 'indicatif' => '+371'],
            ['name' => 'Lebanon', 'indicatif' => '+961'],
            ['name' => 'Lesotho', 'indicatif' => '+266'],
            ['name' => 'Liberia', 'indicatif' => '+231'],
            ['name' => 'Libya', 'indicatif' => '+218'],
            ['name' => 'Liechtenstein', 'indicatif' => '+423'],
            ['name' => 'Lithuania', 'indicatif' => '+370'],
            ['name' => 'Luxembourg', 'indicatif' => '+352'],
            ['name' => 'Macau', 'indicatif' => '+853'],
            ['name' => 'Macedonia', 'indicatif' => '+389'],
            ['name' => 'Madagascar', 'indicatif' => '+261'],
            ['name' => 'Malawi', 'indicatif' => '+265'],
            ['name' => 'Malaysia', 'indicatif' => '+60'],
            ['name' => 'Maldives', 'indicatif' => '+960'],
            ['name' => 'Mali', 'indicatif' => '+223'],
            ['name' => 'Malta', 'indicatif' => '+356'],
            ['name' => 'Marshall Islands', 'indicatif' => '+692'],
            ['name' => 'Mauritania', 'indicatif' => '+222'],
            ['name' => 'Mauritius', 'indicatif' => '+230'],
            ['name' => 'Mayotte', 'indicatif' => '+262'],
            ['name' => 'Mexico', 'indicatif' => '+52'],
            ['name' => 'Micronesia', 'indicatif' => '+691'],
            ['name' => 'Moldova', 'indicatif' => '+373'],
            ['name' => 'Monaco', 'indicatif' => '+377'],
            ['name' => 'Mongolia', 'indicatif' => '+976'],
            ['name' => 'Montenegro', 'indicatif' => '+382'],
            ['name' => 'Montserrat', 'indicatif' => '+1-664'],
            ['name' => 'Morocco', 'indicatif' => '+212'],
            ['name' => 'Mozambique', 'indicatif' => '+258'],
            ['name' => 'Myanmar', 'indicatif' => '+95'],
            ['name' => 'Namibia', 'indicatif' => '+264'],
            ['name' => 'Nauru', 'indicatif' => '+674'],
            ['name' => 'Nepal', 'indicatif' => '+977'],
            ['name' => 'Netherlands', 'indicatif' => '+31'],
            ['name' => 'Netherlands Antilles', 'indicatif' => '+599'],
            ['name' => 'New Caledonia', 'indicatif' => '+687'],
            ['name' => 'New Zealand', 'indicatif' => '+64'],
            ['name' => 'Nicaragua', 'indicatif' => '+505'],
            ['name' => 'Niger', 'indicatif' => '+227'],
            ['name' => 'Nigeria', 'indicatif' => '+234'],
            ['name' => 'Niue', 'indicatif' => '+683'],
            ['name' => 'North Korea', 'indicatif' => '+850'],
            ['name' => 'Northern Mariana Islands', 'indicatif' => '+1-670'],
            ['name' => 'Norway', 'indicatif' => '+47'],
            ['name' => 'Oman', 'indicatif' => '+968'],
            ['name' => 'Pakistan', 'indicatif' => '+92'],
            ['name' => 'Palau', 'indicatif' => '+680'],
            ['name' => 'Palestine', 'indicatif' => '+970'],
            ['name' => 'Panama', 'indicatif' => '+507'],
            ['name' => 'Papua New Guinea', 'indicatif' => '+675'],
            ['name' => 'Paraguay', 'indicatif' => '+595'],
            ['name' => 'Peru', 'indicatif' => '+51'],
            ['name' => 'Philippines', 'indicatif' => '+63'],
            ['name' => 'Pitcairn', 'indicatif' => '+64'],
            ['name' => 'Poland', 'indicatif' => '+48'],
            ['name' => 'Portugal', 'indicatif' => '+351'],
            ['name' => 'Puerto Rico', 'indicatif' => '+1-787'],
            ['name' => 'Qatar', 'indicatif' => '+974'],
            ['name' => 'Republic of the Congo', 'indicatif' => '+242'],
            ['name' => 'Reunion', 'indicatif' => '+262'],
            ['name' => 'Romania', 'indicatif' => '+40'],
            ['name' => 'Russia', 'indicatif' => '+7'],
            ['name' => 'Rwanda', 'indicatif' => '+250'],
            ['name' => 'Saint Barthelemy', 'indicatif' => '+590'],
            ['name' => 'Saint Helena', 'indicatif' => '+290'],
            ['name' => 'Saint Kitts and Nevis', 'indicatif' => '+1-869'],
            ['name' => 'Saint Lucia', 'indicatif' => '+1-758'],
            ['name' => 'Saint Martin', 'indicatif' => '+590'],
            ['name' => 'Saint Pierre and Miquelon', 'indicatif' => '+508'],
            ['name' => 'Saint Vincent and the Grenadines', 'indicatif' => '+1-784'],
            ['name' => 'Samoa', 'indicatif' => '+685'],
            ['name' => 'San Marino', 'indicatif' => '+378'],
            ['name' => 'Sao Tome and Principe', 'indicatif' => '+239'],
            ['name' => 'Saudi Arabia', 'indicatif' => '+966'],
            ['name' => 'Senegal', 'indicatif' => '+221'],
            ['name' => 'Serbia', 'indicatif' => '+381'],
            ['name' => 'Seychelles', 'indicatif' => '+248'],
            ['name' => 'Sierra Leone', 'indicatif' => '+232'],
            ['name' => 'Singapore', 'indicatif' => '+65'],
            ['name' => 'Sint Maarten', 'indicatif' => '+1-721'],
            ['name' => 'Slovakia', 'indicatif' => '+421'],
            ['name' => 'Slovenia', 'indicatif' => '+386'],
            ['name' => 'Solomon Islands', 'indicatif' => '+677'],
            ['name' => 'Somalia', 'indicatif' => '+252'],
            ['name' => 'South Africa', 'indicatif' => '+27'],
            ['name' => 'South Korea', 'indicatif' => '+82'],
            ['name' => 'South Sudan', 'indicatif' => '+211'],
            ['name' => 'Spain', 'indicatif' => '+34'],
            ['name' => 'Sri Lanka', 'indicatif' => '+94'],
            ['name' => 'Sudan', 'indicatif' => '+249'],
            ['name' => 'Suriname', 'indicatif' => '+597'],
            ['name' => 'Svalbard and Jan Mayen', 'indicatif' => '+47'],
            ['name' => 'Swaziland', 'indicatif' => '+268'],
            ['name' => 'Sweden', 'indicatif' => '+46'],
            ['name' => 'Switzerland', 'indicatif' => '+41'],
            ['name' => 'Syria', 'indicatif' => '+963'],
            ['name' => 'Taiwan', 'indicatif' => '+886'],
            ['name' => 'Tajikistan', 'indicatif' => '+992'],
            ['name' => 'Tanzania', 'indicatif' => '+255'],
            ['name' => 'Thailand', 'indicatif' => '+66'],
            ['name' => 'Timor-Leste', 'indicatif' => '+670'],
            ['name' => 'Togo', 'indicatif' => '+228'],
            ['name' => 'Tokelau', 'indicatif' => '+690'],
            ['name' => 'Tonga', 'indicatif' => '+676'],
            ['name' => 'Trinidad and Tobago', 'indicatif' => '+1-868'],
            ['name' => 'Tunisia', 'indicatif' => '+216'],
            ['name' => 'Turkey', 'indicatif' => '+90'],
            ['name' => 'Turkmenistan', 'indicatif' => '+993'],
            ['name' => 'Turks and Caicos Islands', 'indicatif' => '+1-649'],
            ['name' => 'Tuvalu', 'indicatif' => '+688'],
            ['name' => 'U.S. Virgin Islands', 'indicatif' => '+1-340'],
            ['name' => 'Uganda', 'indicatif' => '+256'],
            ['name' => 'Ukraine', 'indicatif' => '+380'],
            ['name' => 'United Arab Emirates', 'indicatif' => '+971'],
            ['name' => 'United Kingdom', 'indicatif' => '+44'],
            ['name' => 'United States', 'indicatif' => '+1'],
            ['name' => 'Uruguay', 'indicatif' => '+598'],
            ['name' => 'Uzbekistan', 'indicatif' => '+998'],
            ['name' => 'Vanuatu', 'indicatif' => '+678'],
            ['name' => 'Vatican', 'indicatif' => '+379'],
            ['name' => 'Vatican City', 'indicatif' => '+379'],
            ['name' => 'Venezuela', 'indicatif' => '+58'],
            ['name' => 'Vietnam', 'indicatif' => '+84'],
            ['name' => 'Wallis and Futuna', 'indicatif' => '+681'],
            ['name' => 'Western Sahara', 'indicatif' => '+212'],
            ['name' => 'Yemen', 'indicatif' => '+967'],
            ['name' => 'Zambia', 'indicatif' => '+260'],
            ['name' => 'Zimbabwe', 'indicatif' => '+263'],
            // Ajoutez d'autres pays avec leurs indicatifs ici
        ];

        // Insertion des données dans la table 'pays'
        foreach ($pays as $paysData) {
            DB::table('pays')->insert($paysData);
        }
    }
}
